ALTER TABLE contable_comprobantes
ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE,
ADD COLUMN IF NOT EXISTS neto_gravado NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS neto_no_gravado NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_iva NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS percepciones_iibb NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS percepciones_iva NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS lineas_detalle JSONB DEFAULT '[]'::jsonb;
